services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
      - ~/Downloads/VocalNote_models:/app/models
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents host node_modules from overwriting container node_modules
    depends_on:
      - backend
